repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [s3fs, paramiko, tenacity, types-paramiko, pyarrow, azure-storage-file-datalake, azure-identity, opentelemetry-api]
        args: [--config-file=pyproject.toml]
        files: ^src/
