name: Bug Report
description: Report a bug in remote-store
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: remote-store version
      description: "Output of `python -c \"import remote_store; print(remote_store.__version__)\"`"
      placeholder: "0.4.2"
    validations:
      required: true

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which backend are you using?
      options:
        - Local filesystem
        - S3 (boto3/s3fs)
        - S3 (PyArrow)
        - SFTP
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "Output of `python --version`"
      placeholder: "3.12.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Ubuntu 24.04 / Windows 11 / macOS 15"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include tracebacks if applicable.
      render: text
    validations:
      required: true
