#!/usr/bin/env python3
"""BK-422: the process files agents re-read may not grow without a recorded raise.

Every byte of ``CLAUDE.md``, an output style (``.claude/settings.json`` selects
one for every session), a skill or an agent definition is re-read on every
later call of the session that loads it, and again in every subagent; the
measurement is ``sdd/research/token-usage/report.md``. Nothing priced their
growth, so this gate is a ratchet on their **total**, held in
``sdd/process-budget.json``:

* **Growth fails.** The current total may not exceed the recorded ``total``.
  Growth that is wanted is a *raise*: ``--raise --item <ID> --reason <text>``
  records it in the file's ``raises`` register (DRIFT-RULES Rule 6), so it is
  argued in the diff instead of accumulating unseen.
* **An unrecorded shrink fails too.** Below ``total × (1 − SLACK)`` the check
  asks for ``--update``, which locks the lower total in. Without that, a cut
  would leave credit that later growth spends silently.

Sizes are bytes with ``\\r\\n`` counted as ``\\n``, so a Windows checkout
measures the same as CI.

Bounds (DRIFT-RULES Rule 7)
---------------------------
* **Bytes, not tokens, and not reads.** A file every reviewer loads counts the
  same as one read once a month; the budget prices size only.
* **The total, not each file.** One file may grow while another shrinks by as
  much. That is the intent: growth costs a removal somewhere in the set.
* **A cut inside the slack is not locked in.** A total down to
  ``int(total × (1 − SLACK))`` passes without ``--update``, so a cut that small
  can be re-grown later with no raise recorded.
* **The file is checked against itself, not its history.** Every run requires
  ``total`` to equal the sum of ``files``, no key beyond the known ones, and
  every ``raises`` entry to carry an item, a reason and ``from < to``. A hand
  edit raising ``total`` and one ``files`` entry together, or adding a
  well-formed raise, passes: only the diff shows it, as it shows any raise.
* **Only what ``globs`` match.** Text the repo's hooks under ``.claude/hooks/``
  print into a session is generated by code and not measured here. Claude
  Code's own system prompt and tool schemas, the user's global instructions
  and memory sit outside the repo and outside this gate.
* **Per branch, and in-slack cuts accumulate.** Each PR is checked against the
  total its own branch records. Two PRs that each cut within the slack pass
  alone and can together fall below the floor once both merge, so the next PR
  on that base fails for a cut it did not make; the shrink message says so.
  Two PRs that each run ``--update`` or ``--raise`` rewrite the same keys and
  conflict textually; re-run the command on the merged tree.

Run with::

    hatch run check-process-budget
    hatch run preflight      # bundled
    hatch run docs-gate      # bundled; ci.yml routes .claude/ and CLAUDE.md
                             # diffs to the docs job, not the CODE_PAT lint job
    python scripts/check_process_budget.py --update
    python scripts/check_process_budget.py --raise --item BK-422 --reason "..."

Exit codes: ``0`` within budget (or the file was rewritten), ``1`` over or under
it, each budgeted file's change since the last lock-in printed (Rule 2), or a
glob matching no file; ``2`` a refused update, or a budget file that is missing,
not JSON, lacks a key, or contradicts itself.

Drift-gate::

    kind:       rule
    rule: the total size of the process files agents re-read (CLAUDE.md, output styles, skills,
        agent definitions, CLAUDE-REFERENCE.md, the trace schema) neither exceeds nor falls unrecorded
        below the total sdd/process-budget.json records, and that file is consistent with itself:
        total equals the sum of its files and every raise entry carries an item and a reason
    domain:     process
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUDGET = Path("sdd/process-budget.json")

# Held here, not in the budget file, so loosening it is a reviewed code change.
SLACK = 0.02

_ITEM_RX = re.compile(r"^(BL|BK|BUG|ID)-\d+$")


def measure(root: Path, globs: list[str]) -> dict[str, int]:
    """Size of every file the globs match, keyed by repo-relative POSIX path."""
    sizes: dict[str, int] = {}
    for pattern in globs:
        for path in sorted(root.glob(pattern)):
            if path.is_file():
                rel = path.relative_to(root).as_posix()
                sizes[rel] = len(path.read_bytes().replace(b"\r\n", b"\n"))
    return sizes


_KEYS = ("globs", "total", "files")
_OPTIONAL = frozenset({"_doc", "raises"})


def load(root: Path) -> dict:
    """The budget, with every key ``main`` reads present; raises on anything less."""
    budget = json.loads((root / BUDGET).read_text(encoding="utf-8"))
    for key in _KEYS:
        budget[key]  # noqa: B018 - a missing key raises KeyError here, not mid-check
    return budget


def integrity(budget: dict) -> list[str]:
    """What the file contradicts about itself; it carries no history, so no more."""
    problems = []
    unknown = sorted(set(budget) - set(_KEYS) - _OPTIONAL)
    if unknown:
        problems.append(f"unknown key(s): {', '.join(unknown)}")
    recorded = sum(budget["files"].values())
    if budget["total"] != recorded:
        problems.append(f"total {budget['total']} is not the sum of files ({recorded})")
    for i, entry in enumerate(budget.get("raises", [])):
        ok = (
            isinstance(entry, dict)
            and isinstance(entry.get("item"), str)
            and _ITEM_RX.match(entry["item"])
            and isinstance(entry.get("reason"), str)
            and entry["reason"].strip()
            and isinstance(entry.get("from"), int)
            and isinstance(entry.get("to"), int)
            and entry["from"] < entry["to"]
        )
        if not ok:
            problems.append(f"raises[{i}] needs an item, a reason, and from < to")
    return problems


def save(root: Path, budget: dict) -> None:
    (root / BUDGET).write_text(json.dumps(budget, indent=2) + "\n", encoding="utf-8")


def deltas(recorded: dict[str, int], current: dict[str, int]) -> list[str]:
    """One line per file whose size moved since the last lock-in, largest first."""
    rows = []
    for path in sorted(recorded.keys() | current.keys()):
        old, new = recorded.get(path), current.get(path)
        if old == new:
            continue
        diff = (new or 0) - (old or 0)
        state = "new" if old is None else "removed" if new is None else f"{old} -> {new}"
        rows.append((abs(diff), f"  {diff:+7d}  {path} ({state})"))
    return [text for _, text in sorted(rows, key=lambda r: -r[0])]


def lock(budget: dict, current: dict[str, int]) -> dict:
    budget["total"] = sum(current.values())
    budget["files"] = current
    return budget


def main(argv: list[str] | None = None, root: Path = ROOT) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--update", action="store_true", help="lock in a lower total after a cut")
    parser.add_argument("--raise", dest="raise_", action="store_true", help="record a wanted growth")
    parser.add_argument("--item", help="backlog ID owning the raise")
    parser.add_argument("--reason", help="why the growth is worth its cost")
    parser.add_argument("--root", type=Path, default=None, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root or root

    try:
        budget = load(root)
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as exc:
        print(
            f"Process budget file unreadable: {BUDGET.as_posix()}: {type(exc).__name__}: {exc}\n"
            "Restore it from the base branch; after a merge conflict, re-run --update or --raise "
            "on the merged tree instead of hand-merging the numbers.",
            file=sys.stderr,
        )
        return 2
    problems = integrity(budget)
    if problems:
        print(f"Process budget file inconsistent: {BUDGET.as_posix()}:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            "It is written by --update and --raise only; restore it from the base branch and re-run the one you meant.",
            file=sys.stderr,
        )
        return 2
    dead = [g for g in budget["globs"] if not any(p.is_file() for p in root.glob(g))]
    if dead:
        # A renamed file would otherwise leave the budget silently (Rule 3).
        print(f"Budget glob(s) match no file: {', '.join(dead)}", file=sys.stderr)
        return 1
    current = measure(root, budget["globs"])
    total, recorded = budget["total"], budget["files"]
    now = sum(current.values())
    floor = int(total * (1 - SLACK))

    if args.update:
        if now > total:
            print(f"Refused: {now} bytes exceeds the recorded {total}; growth is a --raise.", file=sys.stderr)
            return 2
        save(root, lock(budget, current))
        print(f"Locked in {now} bytes (was {total}).")
        return 0

    if args.raise_:
        if not (args.item and _ITEM_RX.match(args.item) and args.reason and args.reason.strip()):
            print("Refused: --raise needs --item <PREFIX-NNN> and a non-empty --reason.", file=sys.stderr)
            return 2
        if now <= total:
            print(f"Refused: {now} bytes fits the recorded {total}; nothing to raise.", file=sys.stderr)
            return 2
        budget.setdefault("raises", []).append(
            {"item": args.item, "from": total, "to": now, "reason": args.reason.strip()}
        )
        save(root, lock(budget, current))
        print(f"Raised {total} -> {now} bytes under {args.item}.")
        return 0

    if floor <= now <= total:
        print(f"Process files within budget: {now} of {total} bytes ({len(current)} files).")
        return 0

    over = now > total
    if over:
        head = f"Process files grew: {now} bytes against a recorded {total} (+{now - total})."
        fix = "Cut as much elsewhere in the set, or record the growth with --raise --item <ID> --reason <text>."
    else:
        head = f"Process files shrank below the slack: {now} bytes against a recorded {total}."
        fix = (
            "Lock the cut in with --update, so later growth cannot spend it unseen. "
            "If this PR made no cut, earlier in-slack cuts have accumulated on the base: "
            "run --update and commit the budget file all the same."
        )
    print(head, file=sys.stderr)
    for row in deltas(recorded, current):
        print(row, file=sys.stderr)
    print(f"\n{fix}\n(scripts/check_process_budget.py; budget in {BUDGET.as_posix()})", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
